version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - REACT_APP_STAGE=prod npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
